countries_to_codes = {'afghanistan': 'AF',
 'åland islands': 'AX',
 'albania': 'AL',
 'algeria': 'DZ',
 'american samoa': 'AS',
 'andorra': 'AD',
 'angola': 'AO',
 'anguilla': 'AI',
 'antarctica': 'AQ',
 'antigua and barbuda': 'AG',
 'argentina': 'AR',
 'armenia': 'AM',
 'aruba': 'AW',
 'australia': 'AU',
 'austria': 'AT',
 'azerbaijan': 'AZ',
 'bahamas (the)': 'BS',
 'bahrain': 'BH',
 'bangladesh': 'BD',
 'barbados': 'BB',
 'belarus': 'BY',
 'belgium': 'BE',
 'belize': 'BZ',
 'benin': 'BJ',
 'bermuda': 'BM',
 'bhutan': 'BT',
 'bolivia (plurinational state of)': 'BO',
 'bonaire, sint eustatius and saba': 'BQ',
 'bosnia and herzegovina': 'BA',
 'botswana': 'BW',
 'bouvet island': 'BV',
 'brazil': 'BR',
 'british indian ocean territory (the)': 'IO',
 'brunei darussalam': 'BN',
 'bulgaria': 'BG',
 'burkina faso': 'BF',
 'burundi': 'BI',
 'cabo verde': 'CV',
 'cambodia': 'KH',
 'cameroon': 'CM',
 'canada': 'CA',
 'cayman islands (the)': 'KY',
 'central african republic (the)': 'CF',
 'chad': 'TD',
 'chile': 'CL',
 'china': 'CN',
 'christmas island': 'CX',
 'cocos (keeling) islands (the)': 'CC',
 'colombia': 'CO',
 'comoros (the)': 'KM',
 'congo (the democratic republic of the)': 'CD',
 'congo (the)': 'CG',
 'cook islands (the)': 'CK',
 'costa rica': 'CR',
 "côte d'ivoire": 'CI',
 'croatia': 'HR',
 'cuba': 'CU',
 'curaçao': 'CW',
 'cyprus': 'CY',
 'czechia': 'CZ',
 'denmark': 'DK',
 'djibouti': 'DJ',
 'dominica': 'DM',
 'dominican republic (the)': 'DO',
 'ecuador': 'EC',
 'egypt': 'EG',
 'el salvador': 'SV',
 'equatorial guinea': 'GQ',
 'eritrea': 'ER',
 'estonia': 'EE',
 'eswatini': 'SZ',
 'ethiopia': 'ET',
 'falkland islands (the) [malvinas]': 'FK',
 'faroe islands (the)': 'FO',
 'fiji': 'FJ',
 'finland': 'FI',
 'france': 'FR',
 'french guiana': 'GF',
 'french polynesia': 'PF',
 'french southern territories (the)': 'TF',
 'gabon': 'GA',
 'gambia (the)': 'GM',
 'georgia': 'GE',
 'germany': 'DE',
 'ghana': 'GH',
 'gibraltar': 'GI',
 'greece': 'GR',
 'greenland': 'GL',
 'grenada': 'GD',
 'guadeloupe': 'GP',
 'guam': 'GU',
 'guatemala': 'GT',
 'guernsey': 'GG',
 'guinea': 'GN',
 'guinea-bissau': 'GW',
 'guyana': 'GY',
 'haiti': 'HT',
 'heard island and mcdonald islands': 'HM',
 'holy see (the)': 'VA',
 'honduras': 'HN',
 'hong kong': 'HK',
 'hungary': 'HU',
 'iceland': 'IS',
 'india': 'IN',
 'indonesia': 'ID',
 'iran (islamic republic of)': 'IR',
 'iraq': 'IQ',
 'ireland': 'IE',
 'isle of man': 'IM',
 'israel': 'IL',
 'italy': 'IT',
 'jamaica': 'JM',
 'japan': 'JP',
 'jersey': 'JE',
 'jordan': 'JO',
 'kazakhstan': 'KZ',
 'kenya': 'KE',
 'kiribati': 'KI',
 "korea (the democratic people's republic of)": 'KP',
 'korea (the republic of)': 'KR',
 'kuwait': 'KW',
 'kyrgyzstan': 'KG',
 "lao people's democratic republic (the)": 'LA',
 'latvia': 'LV',
 'lebanon': 'LB',
 'lesotho': 'LS',
 'liberia': 'LR',
 'libya': 'LY',
 'liechtenstein': 'LI',
 'lithuania': 'LT',
 'luxembourg': 'LU',
 'macao': 'MO',
 'republic of north macedonia': 'MK',
 'madagascar': 'MG',
 'malawi': 'MW',
 'malaysia': 'MY',
 'maldives': 'MV',
 'mali': 'ML',
 'malta': 'MT',
 'marshall islands (the)': 'MH',
 'martinique': 'MQ',
 'mauritania': 'MR',
 'mauritius': 'MU',
 'mayotte': 'YT',
 'mexico': 'MX',
 'micronesia (federated states of)': 'FM',
 'moldova (the republic of)': 'MD',
 'monaco': 'MC',
 'mongolia': 'MN',
 'montenegro': 'ME',
 'montserrat': 'MS',
 'morocco': 'MA',
 'mozambique': 'MZ',
 'myanmar': 'MM',
 'namibia': 'NA',
 'nauru': 'NR',
 'nepal': 'NP',
 'netherlands (the)': 'NL',
 'new caledonia': 'NC',
 'new zealand': 'NZ',
 'nicaragua': 'NI',
 'niger (the)': 'NE',
 'nigeria': 'NG',
 'niue': 'NU',
 'norfolk island': 'NF',
 'northern mariana islands (the)': 'MP',
 'norway': 'NO',
 'oman': 'OM',
 'pakistan': 'PK',
 'palau': 'PW',
 'palestine, state of': 'PS',
 'panama': 'PA',
 'papua new guinea': 'PG',
 'paraguay': 'PY',
 'peru': 'PE',
 'philippines (the)': 'PH',
 'pitcairn': 'PN',
 'poland': 'PL',
 'portugal': 'PT',
 'puerto rico': 'PR',
 'qatar': 'QA',
 'réunion': 'RE',
 'romania': 'RO',
 'russian federation (the)': 'RU',
 'rwanda': 'RW',
 'saint barthélemy': 'BL',
 'saint helena, ascension and tristan da cunha': 'SH',
 'saint kitts and nevis': 'KN',
 'saint lucia': 'LC',
 'saint martin (french part)': 'MF',
 'saint pierre and miquelon': 'PM',
 'saint vincent and the grenadines': 'VC',
 'samoa': 'WS',
 'san marino': 'SM',
 'sao tome and principe': 'ST',
 'saudi arabia': 'SA',
 'senegal': 'SN',
 'serbia': 'RS',
 'seychelles': 'SC',
 'sierra leone': 'SL',
 'singapore': 'SG',
 'sint maarten (dutch part)': 'SX',
 'slovakia': 'SK',
 'slovenia': 'SI',
 'solomon islands': 'SB',
 'somalia': 'SO',
 'south africa': 'ZA',
 'south georgia and the south sandwich islands': 'GS',
 'south sudan': 'SS',
 'spain': 'ES',
 'sri lanka': 'LK',
 'sudan (the)': 'SD',
 'suriname': 'SR',
 'svalbard and jan mayen': 'SJ',
 'sweden': 'SE',
 'switzerland': 'CH',
 'syrian arab republic': 'SY',
 'taiwan (province of china)': 'TW',
 'tajikistan': 'TJ',
 'tanzania, united republic of': 'TZ',
 'thailand': 'TH',
 'timor-leste': 'TL',
 'togo': 'TG',
 'tokelau': 'TK',
 'tonga': 'TO',
 'trinidad and tobago': 'TT',
 'tunisia': 'TN',
 'turkey': 'TR',
 'turkmenistan': 'TM',
 'turks and caicos islands (the)': 'TC',
 'tuvalu': 'TV',
 'uganda': 'UG',
 'ukraine': 'UA',
 'united arab emirates (the)': 'AE',
 'united kingdom of great britain and northern ireland (the)': 'GB',
 'united states minor outlying islands (the)': 'UM',
 'united states of america (the)': 'US',
 'uruguay': 'UY',
 'uzbekistan': 'UZ',
 'vanuatu': 'VU',
 'venezuela (bolivarian republic of)': 'VE',
 'viet nam': 'VN',
 'virgin islands (british)': 'VG',
 'virgin islands (u.s.)': 'VI',
 'wallis and futuna': 'WF',
 'western sahara': 'EH',
 'yemen': 'YE',
 'zambia': 'ZM',
 'zimbabwe': 'ZW'}


codes_to_countries = {'AF': 'afghanistan',
 'AX': 'åland islands',
 'AL': 'albania',
 'DZ': 'algeria',
 'AS': 'american samoa',
 'AD': 'andorra',
 'AO': 'angola',
 'AI': 'anguilla',
 'AQ': 'antarctica',
 'AG': 'antigua and barbuda',
 'AR': 'argentina',
 'AM': 'armenia',
 'AW': 'aruba',
 'AU': 'australia',
 'AT': 'austria',
 'AZ': 'azerbaijan',
 'BS': 'bahamas (the)',
 'BH': 'bahrain',
 'BD': 'bangladesh',
 'BB': 'barbados',
 'BY': 'belarus',
 'BE': 'belgium',
 'BZ': 'belize',
 'BJ': 'benin',
 'BM': 'bermuda',
 'BT': 'bhutan',
 'BO': 'bolivia (plurinational state of)',
 'BQ': 'bonaire, sint eustatius and saba',
 'BA': 'bosnia and herzegovina',
 'BW': 'botswana',
 'BV': 'bouvet island',
 'BR': 'brazil',
 'IO': 'british indian ocean territory (the)',
 'BN': 'brunei darussalam',
 'BG': 'bulgaria',
 'BF': 'burkina faso',
 'BI': 'burundi',
 'CV': 'cabo verde',
 'KH': 'cambodia',
 'CM': 'cameroon',
 'CA': 'canada',
 'KY': 'cayman islands (the)',
 'CF': 'central african republic (the)',
 'TD': 'chad',
 'CL': 'chile',
 'CN': 'china',
 'CX': 'christmas island',
 'CC': 'cocos (keeling) islands (the)',
 'CO': 'colombia',
 'KM': 'comoros (the)',
 'CD': 'congo (the democratic republic of the)',
 'CG': 'congo (the)',
 'CK': 'cook islands (the)',
 'CR': 'costa rica',
 'CI': "côte d'ivoire",
 'HR': 'croatia',
 'CU': 'cuba',
 'CW': 'curaçao',
 'CY': 'cyprus',
 'CZ': 'czechia',
 'DK': 'denmark',
 'DJ': 'djibouti',
 'DM': 'dominica',
 'DO': 'dominican republic (the)',
 'EC': 'ecuador',
 'EG': 'egypt',
 'SV': 'el salvador',
 'GQ': 'equatorial guinea',
 'ER': 'eritrea',
 'EE': 'estonia',
 'SZ': 'eswatini',
 'ET': 'ethiopia',
 'FK': 'falkland islands (the) [malvinas]',
 'FO': 'faroe islands (the)',
 'FJ': 'fiji',
 'FI': 'finland',
 'FR': 'france',
 'GF': 'french guiana',
 'PF': 'french polynesia',
 'TF': 'french southern territories (the)',
 'GA': 'gabon',
 'GM': 'gambia (the)',
 'GE': 'georgia',
 'DE': 'germany',
 'GH': 'ghana',
 'GI': 'gibraltar',
 'GR': 'greece',
 'GL': 'greenland',
 'GD': 'grenada',
 'GP': 'guadeloupe',
 'GU': 'guam',
 'GT': 'guatemala',
 'GG': 'guernsey',
 'GN': 'guinea',
 'GW': 'guinea-bissau',
 'GY': 'guyana',
 'HT': 'haiti',
 'HM': 'heard island and mcdonald islands',
 'VA': 'holy see (the)',
 'HN': 'honduras',
 'HK': 'hong kong',
 'HU': 'hungary',
 'IS': 'iceland',
 'IN': 'india',
 'ID': 'indonesia',
 'IR': 'iran (islamic republic of)',
 'IQ': 'iraq',
 'IE': 'ireland',
 'IM': 'isle of man',
 'IL': 'israel',
 'IT': 'italy',
 'JM': 'jamaica',
 'JP': 'japan',
 'JE': 'jersey',
 'JO': 'jordan',
 'KZ': 'kazakhstan',
 'KE': 'kenya',
 'KI': 'kiribati',
 'KP': "korea (the democratic people's republic of)",
 'KR': 'korea (the republic of)',
 'KW': 'kuwait',
 'KG': 'kyrgyzstan',
 'LA': "lao people's democratic republic (the)",
 'LV': 'latvia',
 'LB': 'lebanon',
 'LS': 'lesotho',
 'LR': 'liberia',
 'LY': 'libya',
 'LI': 'liechtenstein',
 'LT': 'lithuania',
 'LU': 'luxembourg',
 'MO': 'macao',
 'MK': 'republic of north macedonia',
 'MG': 'madagascar',
 'MW': 'malawi',
 'MY': 'malaysia',
 'MV': 'maldives',
 'ML': 'mali',
 'MT': 'malta',
 'MH': 'marshall islands (the)',
 'MQ': 'martinique',
 'MR': 'mauritania',
 'MU': 'mauritius',
 'YT': 'mayotte',
 'MX': 'mexico',
 'FM': 'micronesia (federated states of)',
 'MD': 'moldova (the republic of)',
 'MC': 'monaco',
 'MN': 'mongolia',
 'ME': 'montenegro',
 'MS': 'montserrat',
 'MA': 'morocco',
 'MZ': 'mozambique',
 'MM': 'myanmar',
 'NA': 'namibia',
 'NR': 'nauru',
 'NP': 'nepal',
 'NL': 'netherlands (the)',
 'NC': 'new caledonia',
 'NZ': 'new zealand',
 'NI': 'nicaragua',
 'NE': 'niger (the)',
 'NG': 'nigeria',
 'NU': 'niue',
 'NF': 'norfolk island',
 'MP': 'northern mariana islands (the)',
 'NO': 'norway',
 'OM': 'oman',
 'PK': 'pakistan',
 'PW': 'palau',
 'PS': 'palestine, state of',
 'PA': 'panama',
 'PG': 'papua new guinea',
 'PY': 'paraguay',
 'PE': 'peru',
 'PH': 'philippines (the)',
 'PN': 'pitcairn',
 'PL': 'poland',
 'PT': 'portugal',
 'PR': 'puerto rico',
 'QA': 'qatar',
 'RE': 'réunion',
 'RO': 'romania',
 'RU': 'russian federation (the)',
 'RW': 'rwanda',
 'BL': 'saint barthélemy',
 'SH': 'saint helena, ascension and tristan da cunha',
 'KN': 'saint kitts and nevis',
 'LC': 'saint lucia',
 'MF': 'saint martin (french part)',
 'PM': 'saint pierre and miquelon',
 'VC': 'saint vincent and the grenadines',
 'WS': 'samoa',
 'SM': 'san marino',
 'ST': 'sao tome and principe',
 'SA': 'saudi arabia',
 'SN': 'senegal',
 'RS': 'serbia',
 'SC': 'seychelles',
 'SL': 'sierra leone',
 'SG': 'singapore',
 'SX': 'sint maarten (dutch part)',
 'SK': 'slovakia',
 'SI': 'slovenia',
 'SB': 'solomon islands',
 'SO': 'somalia',
 'ZA': 'south africa',
 'GS': 'south georgia and the south sandwich islands',
 'SS': 'south sudan',
 'ES': 'spain',
 'LK': 'sri lanka',
 'SD': 'sudan (the)',
 'SR': 'suriname',
 'SJ': 'svalbard and jan mayen',
 'SE': 'sweden',
 'CH': 'switzerland',
 'SY': 'syrian arab republic',
 'TW': 'taiwan (province of china)',
 'TJ': 'tajikistan',
 'TZ': 'tanzania, united republic of',
 'TH': 'thailand',
 'TL': 'timor-leste',
 'TG': 'togo',
 'TK': 'tokelau',
 'TO': 'tonga',
 'TT': 'trinidad and tobago',
 'TN': 'tunisia',
 'TR': 'turkey',
 'TM': 'turkmenistan',
 'TC': 'turks and caicos islands (the)',
 'TV': 'tuvalu',
 'UG': 'uganda',
 'UA': 'ukraine',
 'AE': 'united arab emirates (the)',
 'GB': 'united kingdom of great britain and northern ireland (the)',
 'UM': 'united states minor outlying islands (the)',
 'US': 'united states of america (the)',
 'UY': 'uruguay',
 'UZ': 'uzbekistan',
 'VU': 'vanuatu',
 'VE': 'venezuela (bolivarian republic of)',
 'VN': 'viet nam',
 'VG': 'virgin islands (british)',
 'VI': 'virgin islands (u.s.)',
 'WF': 'wallis and futuna',
 'EH': 'western sahara',
 'YE': 'yemen',
 'ZM': 'zambia',
 'ZW': 'zimbabwe'}